CREATE TYPE public.app_role AS ENUM ('admin','user');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_roles ON public.user_roles FOR SELECT TO authenticated USING (user_id=auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
REVOKE ALL ON FUNCTION public.has_role(uuid,public.app_role) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role) TO authenticated;
CREATE TABLE public.profiles (id uuid PRIMARY KEY, name text NOT NULL, username text NOT NULL UNIQUE CHECK(username ~ '^[a-z0-9._-]{3,40}$'), last_login timestamptz, last_logout timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profile_read ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY profile_create ON public.profiles FOR INSERT TO authenticated WITH CHECK(id=auth.uid());
CREATE POLICY profile_update ON public.profiles FOR UPDATE TO authenticated USING(id=auth.uid()) WITH CHECK(id=auth.uid());
CREATE TABLE public.entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES public.profiles(id), client_id text NOT NULL, type text NOT NULL CHECK(type ~ '^(q_[a-z_]+|takafu|innovation|inspire|quiz_admin|quiz_teachers|puzzle)$'), text text NOT NULL CHECK(length(text)<=20000), meta jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id,client_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.entries TO authenticated; GRANT ALL ON public.entries TO service_role;
ALTER TABLE public.entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY entry_read ON public.entries FOR SELECT TO authenticated USING(owner_id=auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY entry_create ON public.entries FOR INSERT TO authenticated WITH CHECK(owner_id=auth.uid());
CREATE POLICY entry_update ON public.entries FOR UPDATE TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());
CREATE POLICY entry_delete ON public.entries FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));
CREATE INDEX entries_owner ON public.entries(owner_id);
CREATE UNIQUE INDEX entries_quiz_once ON public.entries(owner_id,type) WHERE type IN ('quiz_admin','quiz_teachers');
CREATE TABLE public.site_config (id text PRIMARY KEY DEFAULT 'main', welcome jsonb NOT NULL DEFAULT '[]', videos jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.site_config TO authenticated; GRANT ALL ON public.site_config TO service_role;
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY config_read ON public.site_config FOR SELECT TO authenticated USING(true);
CREATE POLICY config_create ON public.site_config FOR INSERT TO authenticated WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE POLICY config_update ON public.site_config FOR UPDATE TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));
CREATE FUNCTION public.touch_updated() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;
CREATE TRIGGER profile_touch BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated();
CREATE TRIGGER entry_touch BEFORE UPDATE ON public.entries FOR EACH ROW EXECUTE FUNCTION public.touch_updated();
CREATE TRIGGER config_touch BEFORE UPDATE ON public.site_config FOR EACH ROW EXECUTE FUNCTION public.touch_updated();
CREATE TRIGGER role_touch BEFORE UPDATE ON public.user_roles FOR EACH ROW EXECUTE FUNCTION public.touch_updated();
CREATE FUNCTION public.ensure_profile() RETURNS public.profiles LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE p public.profiles; uid uuid:=auth.uid(); metadata jsonb:=auth.jwt()->'user_metadata'; BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'Unauthorized'; END IF; SELECT * INTO p FROM public.profiles WHERE id=uid; IF p.id IS NULL THEN INSERT INTO public.profiles(id,name,username) VALUES(uid,coalesce(nullif(metadata->>'name',''),'مستخدمة'),coalesce(nullif(metadata->>'username',''),'user_'||replace(uid::text,'-',''))) RETURNING * INTO p; END IF; RETURN p; END $$;
REVOKE ALL ON FUNCTION public.ensure_profile() FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.ensure_profile() TO authenticated;
ALTER PUBLICATION supabase_realtime ADD TABLE public.entries,public.profiles;